#!/bin/sh
export XDG_CURRENT_DESKTOP=sway

# Start sway
dbus-run-session sway -Vd
# dbus-launch
#sway -Vd

#pour la veille
swayidle -w \
	timeout 300 'swaylock -f -c 000000' \
	timeout 600 'swaymsg "output * dpms off"' \
		resume 'swaymsg "output * dpms on"' \
	before-sleep 'swaylock -f -c 000000'